### ISSUE TITLE
Missing test for NoTabsRule

### ISSUE THREAD

**Issue by roaldnefs** [roaldnefs/salt-lint#23]
Missing test for [NoTabsRule](https://github.com/roaldnefs/salt-lint/blob/master/lib/saltlint/rules/NoTabsRule.py).

**Possible Solution:**
Add  `tests/unit/TestNoTabsRule.py` file. Use [TestLineToLong.py](https://github.com/roaldnefs/salt-lint/blob/master/tests/unit/TestLineToLong.py) as an example for `TestNoTabsRule.py`.

**Comment by kmendler** [comment]
Hi! Can I take this issue?
