### ISSUE TITLE
Missing test for NoWhitespaceRule

### ISSUE THREAD

**Issue by roaldnefs** [roaldnefs/salt-lint#24]
Missing test for [NoWhitespaceRule](https://github.com/roaldnefs/salt-lint/blob/master/lib/saltlint/rules/NoWhitespaceRule.py).

**Possible Solution:**
Add  `tests/unit/NoWhitespaceRule.py` file. Use [TestLineToLong.py](https://github.com/roaldnefs/salt-lint/blob/master/tests/unit/TestLineToLong.py) as an example for `NoWhitespaceRule.py`.

**Comment by kmendler** [comment]
Hi! Can I take this issue?

**Comment by kmendler** [comment]
I didn't test this thoroughly enough... I'll submit a fix asap
