### ISSUE TITLE
Suggested improvements/alternative to file mode implementation

### ISSUE THREAD

**Issue by myii** [roaldnefs/salt-lint#29]
The underlying issue here is that _numbers beginning with zero_ are interpreted as octal in YAML.

https://docs.saltstack.com/en/latest/ref/states/all/salt.states.file.html

> **Warning**
> 
> When using a mode that includes a leading zero you must wrap the value in single quotes. If the value is not wrapped in quotes it will be read by YAML as an integer and evaluated as an octal.

A useful look is how `yamllint` handles these.

https://yamllint.readthedocs.io/en/stable/rules.html#module-yamllint.rules.octal_values

* Ultimately, this is about any numbers beginning with `0`, not just file/dir modes.

I've done test runs on 45 formulas under the [SaltStack Formulas organisation](https://github.com/saltstack-formulas).  Many of them fall afoul of both `207` and `208`.  The problem is that most of these are _false positives_.  The very common usage of 3-digit, unquoted modes (e.g. `755` and `644`) is completely legitimate.  My suggestion is that these shouldn't be flagged as errors/warnings.  There's a simple workaround for this for the time being:

* Apply something similar to: https://github.com/myii/salt-lint/commit/177e3deffa17d47a4660e6096187f31fedbea908
* Add `208` to the ignored list

A more comprehensive solution could be achieved under a new lint ID, which checks for _any_ number with a leading zero (not just file/dir modes), as shown on the `yamllint` docs.  Then users could add both `207` and `208` to the ignore list and use the comprehensive _octal_ bug linter instead.

**Comment by roaldnefs** [comment]
Thanks for the suggestion @myii!

I prefer the comprehensive solution that could be achieved under a new lint ID, which checks for any number with a leading zero (not just file/dir modes), as shown on the `yamllint` docs. 

Please let me know if you would like to take a stab at a PR, otherwise I will try to make an extra rule for it tonight.

**Comment by myii** [comment]
@roaldnefs Thanks for the quick response.  I've got my hands full with SaltStack Formulas at the current time (including rolling out `salt-lint`!) so I won't be able to do much at the moment.  Thanks for offering to take it on.

**Comment by kyentei** [comment]
@myii We have indeed decided that `#207` and `#208` can be added to an exclude list if so desired, and @roaldnefs has added an extra check (`#210`) that simply detects unquoted leading-zero numbers and flags them. Thanks for your suggestions and contribution! :-)

**Comment by myii** [comment]
Fantastic!

**Comment by tacerus** [comment]
Hi,

I wonder, with `210` being in place, is there still a valid reason for `207`? As @myii states, there are valid uses for three digit file modes, ones _without_ a leading zero -  for example `640`, `755`, ...?
